/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteFazenda;

/**
 *
 * @author wesll
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_plantação = new javax.swing.JButton();
        btn_Celeiro = new javax.swing.JButton();
        btn_criar_ocorr = new javax.swing.JButton();
        btn_consultar_ocorr = new javax.swing.JButton();
        Imagem_Celeiro = new javax.swing.JLabel();
        Imagem_Plantação = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_plantação.setText("Plantação");
        btn_plantação.setMaximumSize(new java.awt.Dimension(80, 25));
        btn_plantação.setMinimumSize(new java.awt.Dimension(80, 25));
        getContentPane().add(btn_plantação, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 103, 33));

        btn_Celeiro.setText("Celeiro");
        btn_Celeiro.setMaximumSize(new java.awt.Dimension(80, 25));
        btn_Celeiro.setMinimumSize(new java.awt.Dimension(80, 25));
        btn_Celeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CeleiroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Celeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 100, 30));

        btn_criar_ocorr.setText("Criar Nova");
        getContentPane().add(btn_criar_ocorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 130, 40));

        btn_consultar_ocorr.setText("Consultar status");
        btn_consultar_ocorr.setToolTipText("");
        getContentPane().add(btn_consultar_ocorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 130, 40));

        Imagem_Celeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteFazenda/Celeiro.png"))); // NOI18N
        Imagem_Celeiro.setText("jLabel2");
        getContentPane().add(Imagem_Celeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 250, -1));

        Imagem_Plantação.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteFazenda/Plantação.png"))); // NOI18N
        Imagem_Plantação.setText("jLabel3");
        getContentPane().add(Imagem_Plantação, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 260, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteFazenda/Tela Iniciar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CeleiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CeleiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CeleiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagem_Celeiro;
    private javax.swing.JLabel Imagem_Plantação;
    private javax.swing.JButton btn_Celeiro;
    private javax.swing.JButton btn_consultar_ocorr;
    private javax.swing.JButton btn_criar_ocorr;
    private javax.swing.JButton btn_plantação;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
