ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNC_PERMIS
FOREIGN KEY (cod_permis)
REFERENCES PERMISSAO(cod_permis);

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNC_SETOR
FOREIGN KEY (cod_setor)
REFERENCES SETOR(cod_setor);

ALTER TABLE OCORRENCIA
ADD CONSTRAINT FK_OCOR_SETOR
FOREIGN KEY (cod_setor)
REFERENCES SETOR (cod_setor);

ALTER TABLE OCORRENCIA
ADD CONSTRAINT FK_OCOR_STATUS
FOREIGN KEY (cod_status)
REFERENCES TB_STATUS(cod_status);

ALTER TABLE TAREFA
ADD CONSTRAINT FK_TAREFA_SETOR
FOREIGN KEY (cod_setor)
REFERENCES SETOR(cod_setor);

ALTER TABLE TAREFA
ADD CONSTRAINT FK_TAREFA_STATUS
FOREIGN KEY (cod_status)
REFERENCES TB_STATUS(cod_status);